# Generated by Django 4.0.4 on 2023-04-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='icon_title',
            field=models.ImageField(upload_to='contact_icon'),
        ),
    ]
