# Generated by Django 4.0.4 on 2023-04-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contac', '0002_alter_contact_icon_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='contact',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
