# Generated by Django 4.0.4 on 2023-04-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ccp_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('page_de_garde', models.ImageField(default='', null=True, upload_to='ccp_images')),
            ],
        ),
    ]
