# Generated by Django 4.0.4 on 2023-05-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0002_ccp_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccp',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='ccp_image',
            options={'ordering': ['created']},
        ),
    ]
