# Generated by Django 4.0.4 on 2023-05-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0003_alter_ccp_options_alter_ccp_image_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccp_image',
            name='page_de_garde',
            field=models.ImageField(upload_to='ccp_images'),
        ),
    ]
