# Generated by Django 4.0.4 on 2023-04-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default='fre', null=True, upload_to='profile_student_image'),
        ),
    ]
