# Generated by Django 4.0.4 on 2023-04-29 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filieres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('abre', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('abre', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('icon_title', models.ImageField(upload_to='modules_icon')),
                ('filiere', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='levels.filieres')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('old_prix', models.CharField(max_length=100, unique=True)),
                ('new_prix', models.CharField(max_length=100, unique=True)),
                ('Module', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='levels.modules')),
            ],
        ),
        migrations.AddField(
            model_name='filieres',
            name='level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='levels.levels'),
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('pdf_url', models.CharField(max_length=100, unique=True)),
                ('video_url', models.CharField(max_length=100, unique=True)),
                ('tutorial', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='levels.tutorial')),
            ],
        ),
    ]
