# Generated by Django 4.0.4 on 2023-04-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='is_free',
            field=models.BooleanField(null=True),
        ),
    ]
